### ISSUE TITLE
Support older versions of ActiveSupport

### ISSUE THREAD

**Issue by andrewmarkle** [Shopify/deprecation_toolkit#14]
Hey there! 

Really appreciate you open sourcing this gem! Just saw that you tested against different versions of activesupport and was wondering if it's possible to support older versions of active support (4.2.x). Right now we're still on the upgrade path from Rails 4.2 to 5 and this gem would help us get there!

Happy to open a PR if that helps!

Many thanks! 👌

Andrew

**Comment by rafaelfranca** [comment]
👍. 4.2 is still a supported version by the Rails team, so we should allow people to use this gem to upgrade from it.

**Comment by rafaelfranca** [comment]
Feel free to open a PR.
