### ISSUE TITLE
please add a way to run in production

### ISSUE THREAD

**Issue by fsateler** [Shopify/deprecation_toolkit#47]
Especially for legacy projects that don't have 100% coverage, it would be nice to be able to configure DeprecationToolkit to report the deprecations to a logging service like sentry. AFAICT, currently it is only possible to use this in test environment.

**Comment by rafaelfranca** [comment]
Thank you for the suggestion but this is already supported in Rails itself. You just need to change the `config.active_support.deprecation` to something that log to the service you need.

**Comment by fsateler** [comment]
Hi, 

thanks for your quick response. Indeed, that was my first thought, but I would prefer to make use of the DeprecatedToolkit database: I don't want to spam my error notification service with things I already know!

So, maybe this can be retitled to "please expose a way to easily match the deprecations against the known ones". I wouldn't want to reimplement this database.

**Comment by rscnt** [comment]
@fsateler but you could add this yourself,  either adding the subscriber and then fetching the data from the Collector singleton?
But that would mean running the same twice.
