### ISSUE TITLE
Run deprecated tests

### ISSUE THREAD

**Issue by sobrinho** [Shopify/deprecation_toolkit#69]
We are currently using this script when we fix one exception that is spread over a lot of specs:

```bash
for file in $(git grep module_parent spec/deprecation/ | cut -d: -f1 | sort -u); do
  DEPRECATION_BEHAVIOR=record bin/rspec "${"${file/deprecation\//}"/.yml/_spec.rb}" || return 1;
done
```

Would be nice to have some native solution to get deprecated specs like `bundle exec deprecation_toolkit deprecated` which would print all spec files with deprecation.

And to search something, we could have a simple grep like the script such as `bundle exec deprecation_toolkit deprecated module_parent`.

**Comment by rafaelfranca** [comment]
Good idea. We use a different solution for this so we will not implement it, but pull requests welcome. Closing since we don't plan to implement it.
